/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The BodyPostApiUserLoginLoginPost model module.
* @module model/BodyPostApiUserLoginLoginPost
* @version 3.0.3
*/
export default class BodyPostApiUserLoginLoginPost {
    /**
    * Constructs a new <code>BodyPostApiUserLoginLoginPost</code>.
    * @alias module:model/BodyPostApiUserLoginLoginPost
    * @class
    * @param username {String} 
    * @param password {String} 
    */

    constructor(username, password) {
        
        
        this['username'] = username;
        this['password'] = password;
        
    }

    /**
    * Constructs a <code>BodyPostApiUserLoginLoginPost</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BodyPostApiUserLoginLoginPost} obj Optional instance to populate.
    * @return {module:model/BodyPostApiUserLoginLoginPost} The populated <code>BodyPostApiUserLoginLoginPost</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BodyPostApiUserLoginLoginPost();
                        
            
            if (data.hasOwnProperty('grant_type')) {
                obj['grant_type'] = ApiClient.convertToType(data['grant_type'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('client_secret')) {
                obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} grant_type
    */
    'grant_type' = undefined;
    /**
    * @member {String} username
    */
    'username' = undefined;
    /**
    * @member {String} password
    */
    'password' = undefined;
    /**
    * @member {String} scope
    * @default ''
    */
    'scope' = '';
    /**
    * @member {String} client_id
    */
    'client_id' = undefined;
    /**
    * @member {String} client_secret
    */
    'client_secret' = undefined;




}
