/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetStrikesModel from './GetStrikesModel';

/**
* The Data model module.
* @module model/Data
* @version 3.0.3
*/
export default class Data {
    /**
    * Constructs a new <code>Data</code>.
    * @alias module:model/Data
    * @class
    * @extends module:model/GetStrikesModel
    * @param ust {} 
    * @param exchange {} 
    * @param symbol {} 
    * @param putcall {} 
    * @param ltd {} 
    */

    constructor(ust, exchange, symbol, putcall, ltd) {
        GetStrikesModel.call(this, ust, exchange, symbol, putcall, ltd);
        
        
    }

    /**
    * Constructs a <code>Data</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Data} obj Optional instance to populate.
    * @return {module:model/Data} The populated <code>Data</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Data();
            
            GetStrikesModel.constructFromObject(data, obj);
            
        }
        return obj;
    }





}
