/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The DeltaQuery model module.
* @module model/DeltaQuery
* @version 3.0.3
*/
export default class DeltaQuery {
    /**
    * Constructs a new <code>DeltaQuery</code>.
    * @alias module:model/DeltaQuery
    * @class
    * @param ust {String} 
    * @param exchange {String} 
    * @param symbol {String} 
    * @param ltd {String} 
    * @param startdate {String} 
    * @param enddate {String} 
    */

    constructor(ust, exchange, symbol, ltd, startdate, enddate) {
        
        
        this['ust'] = ust;
        this['exchange'] = exchange;
        this['symbol'] = symbol;
        this['ltd'] = ltd;
        this['startdate'] = startdate;
        this['enddate'] = enddate;
        
    }

    /**
    * Constructs a <code>DeltaQuery</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DeltaQuery} obj Optional instance to populate.
    * @return {module:model/DeltaQuery} The populated <code>DeltaQuery</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeltaQuery();
                        
            
            if (data.hasOwnProperty('ust')) {
                obj['ust'] = ApiClient.convertToType(data['ust'], 'String');
            }
            if (data.hasOwnProperty('exchange')) {
                obj['exchange'] = ApiClient.convertToType(data['exchange'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('ltd')) {
                obj['ltd'] = ApiClient.convertToType(data['ltd'], 'String');
            }
            if (data.hasOwnProperty('startdate')) {
                obj['startdate'] = ApiClient.convertToType(data['startdate'], 'String');
            }
            if (data.hasOwnProperty('enddate')) {
                obj['enddate'] = ApiClient.convertToType(data['enddate'], 'String');
            }
            if (data.hasOwnProperty('option_month')) {
                obj['option_month'] = ApiClient.convertToType(data['option_month'], 'String');
            }
            if (data.hasOwnProperty('underlying_month')) {
                obj['underlying_month'] = ApiClient.convertToType(data['underlying_month'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} ust
    */
    'ust' = undefined;
    /**
    * @member {String} exchange
    */
    'exchange' = undefined;
    /**
    * @member {String} symbol
    */
    'symbol' = undefined;
    /**
    * @member {String} ltd
    */
    'ltd' = undefined;
    /**
    * @member {String} startdate
    */
    'startdate' = undefined;
    /**
    * @member {String} enddate
    */
    'enddate' = undefined;
    /**
    * @member {String} option_month
    */
    'option_month' = undefined;
    /**
    * @member {String} underlying_month
    */
    'underlying_month' = undefined;




}
