/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The HeartBeat model module.
* @module model/HeartBeat
* @version 3.0.3
*/
export default class HeartBeat {
    /**
    * Constructs a new <code>HeartBeat</code>.
    * @alias module:model/HeartBeat
    * @class
    * @param _date {Date} 
    */

    constructor(_date) {
        
        
        this['date'] = _date;
        
    }

    /**
    * Constructs a <code>HeartBeat</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HeartBeat} obj Optional instance to populate.
    * @return {module:model/HeartBeat} The populated <code>HeartBeat</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HeartBeat();
                        
            
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {Date} date
    */
    'date' = undefined;




}
