/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RawOptionPy from './RawOptionPy';

/**
* The Query model module.
* @module model/Query
* @version 3.0.3
*/
export default class Query {
    /**
    * Constructs a new <code>Query</code>.
    * @alias module:model/Query
    * @class
    * @extends module:model/RawOptionPy
    * @param ust {} 
    * @param exchange {} 
    * @param symbol {} 
    * @param ltd {} 
    * @param putcall {} 
    * @param strkpx {} 
    * @param metric {} 
    * @param startdate {} 
    * @param enddate {} 
    */

    constructor(ust, exchange, symbol, ltd, putcall, strkpx, metric, startdate, enddate) {
        RawOptionPy.call(this, ust, exchange, symbol, ltd, putcall, strkpx, metric, startdate, enddate);
        
        
    }

    /**
    * Constructs a <code>Query</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Query} obj Optional instance to populate.
    * @return {module:model/Query} The populated <code>Query</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Query();
            
            RawOptionPy.constructFromObject(data, obj);
            
        }
        return obj;
    }





}
