/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TopOiQuery from './TopOiQuery';

/**
* The Query1 model module.
* @module model/Query1
* @version 3.0.3
*/
export default class Query1 {
    /**
    * Constructs a new <code>Query1</code>.
    * @alias module:model/Query1
    * @class
    * @extends module:model/TopOiQuery
    * @param ust {} 
    * @param exchange {} 
    * @param symbol {} 
    * @param ltd {} 
    * @param putcall {} 
    * @param metric {} 
    */

    constructor(ust, exchange, symbol, ltd, putcall, metric) {
        TopOiQuery.call(this, ust, exchange, symbol, ltd, putcall, metric);
        
        
    }

    /**
    * Constructs a <code>Query1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Query1} obj Optional instance to populate.
    * @return {module:model/Query1} The populated <code>Query1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Query1();
            
            TopOiQuery.constructFromObject(data, obj);
            
        }
        return obj;
    }





}
