/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The RawOptionPy model module.
* @module model/RawOptionPy
* @version 3.0.3
*/
export default class RawOptionPy {
    /**
    * Constructs a new <code>RawOptionPy</code>.
    * @alias module:model/RawOptionPy
    * @class
    * @param ust {String} 
    * @param exchange {String} 
    * @param symbol {String} 
    * @param ltd {String} 
    * @param putcall {module:model/RawOptionPy.PutcallEnum} 
    * @param strkpx {Number} 
    * @param metric {module:model/RawOptionPy.MetricEnum} 
    * @param startdate {String} 
    * @param enddate {String} 
    */

    constructor(ust, exchange, symbol, ltd, putcall, strkpx, metric, startdate, enddate) {
        
        
        this['ust'] = ust;
        this['exchange'] = exchange;
        this['symbol'] = symbol;
        this['ltd'] = ltd;
        this['putcall'] = putcall;
        this['strkpx'] = strkpx;
        this['metric'] = metric;
        this['startdate'] = startdate;
        this['enddate'] = enddate;
        
    }

    /**
    * Constructs a <code>RawOptionPy</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RawOptionPy} obj Optional instance to populate.
    * @return {module:model/RawOptionPy} The populated <code>RawOptionPy</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RawOptionPy();
                        
            
            if (data.hasOwnProperty('ust')) {
                obj['ust'] = ApiClient.convertToType(data['ust'], 'String');
            }
            if (data.hasOwnProperty('exchange')) {
                obj['exchange'] = ApiClient.convertToType(data['exchange'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('ltd')) {
                obj['ltd'] = ApiClient.convertToType(data['ltd'], 'String');
            }
            if (data.hasOwnProperty('putcall')) {
                obj['putcall'] = ApiClient.convertToType(data['putcall'], 'String');
            }
            if (data.hasOwnProperty('strkpx')) {
                obj['strkpx'] = ApiClient.convertToType(data['strkpx'], 'Number');
            }
            if (data.hasOwnProperty('metric')) {
                obj['metric'] = ApiClient.convertToType(data['metric'], 'String');
            }
            if (data.hasOwnProperty('startdate')) {
                obj['startdate'] = ApiClient.convertToType(data['startdate'], 'String');
            }
            if (data.hasOwnProperty('enddate')) {
                obj['enddate'] = ApiClient.convertToType(data['enddate'], 'String');
            }
            if (data.hasOwnProperty('option_month')) {
                obj['option_month'] = ApiClient.convertToType(data['option_month'], 'String');
            }
            if (data.hasOwnProperty('underlying_month')) {
                obj['underlying_month'] = ApiClient.convertToType(data['underlying_month'], 'String');
            }
            if (data.hasOwnProperty('dminus')) {
                obj['dminus'] = ApiClient.convertToType(data['dminus'], 'Number');
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} ust
    */
    'ust' = undefined;
    /**
    * @member {String} exchange
    */
    'exchange' = undefined;
    /**
    * @member {String} symbol
    */
    'symbol' = undefined;
    /**
    * @member {String} ltd
    */
    'ltd' = undefined;
    /**
    * @member {module:model/RawOptionPy.PutcallEnum} putcall
    */
    'putcall' = undefined;
    /**
    * @member {Number} strkpx
    */
    'strkpx' = undefined;
    /**
    * @member {module:model/RawOptionPy.MetricEnum} metric
    */
    'metric' = undefined;
    /**
    * @member {String} startdate
    */
    'startdate' = undefined;
    /**
    * @member {String} enddate
    */
    'enddate' = undefined;
    /**
    * @member {String} option_month
    */
    'option_month' = undefined;
    /**
    * @member {String} underlying_month
    */
    'underlying_month' = undefined;
    /**
    * @member {Number} dminus
    * @default 30
    */
    'dminus' = 30;
    /**
    * @member {module:model/RawOptionPy.OrderEnum} order
    * @default 'asc'
    */
    'order' = 'asc';



    /**
    * Allowed values for the <code>putcall</code> property.
    * @enum {String}
    * @readonly
    */
    static PutcallEnum = {
        /**
         * value: "put"
         * @const
         */
        "put": "put",
        /**
         * value: "call"
         * @const
         */
        "call": "call"    };
    /**
    * Allowed values for the <code>metric</code> property.
    * @enum {String}
    * @readonly
    */
    static MetricEnum = {
        /**
         * value: "underlying_price"
         * @const
         */
        "underlying_price": "underlying_price",
        /**
         * value: "settlement_price"
         * @const
         */
        "settlement_price": "settlement_price",
        /**
         * value: "volume"
         * @const
         */
        "volume": "volume",
        /**
         * value: "open_interest"
         * @const
         */
        "open_interest": "open_interest",
        /**
         * value: "years_until_expiry"
         * @const
         */
        "years_until_expiry": "years_until_expiry",
        /**
         * value: "moneyness"
         * @const
         */
        "moneyness": "moneyness",
        /**
         * value: "dividend_yield"
         * @const
         */
        "dividend_yield": "dividend_yield",
        /**
         * value: "riskfree_rate"
         * @const
         */
        "riskfree_rate": "riskfree_rate",
        /**
         * value: "rawiv"
         * @const
         */
        "rawiv": "rawiv",
        /**
         * value: "delta"
         * @const
         */
        "delta": "delta",
        /**
         * value: "time_value"
         * @const
         */
        "time_value": "time_value"    };
    /**
    * Allowed values for the <code>order</code> property.
    * @enum {String}
    * @readonly
    */
    static OrderEnum = {
        /**
         * value: "asc"
         * @const
         */
        "asc": "asc",
        /**
         * value: "desc"
         * @const
         */
        "desc": "desc"    };

}
