/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SurfaceValue model module.
* @module model/SurfaceValue
* @version 3.0.3
*/
export default class SurfaceValue {
    /**
    * Constructs a new <code>SurfaceValue</code>.
    * @alias module:model/SurfaceValue
    * @class
    * @param var1 {Number} 
    * @param var2 {Number} 
    * @param var3 {Number} 
    * @param var4 {Number} 
    * @param var5 {Number} 
    * @param var6 {Number} 
    * @param var8 {Number} 
    * @param var9 {Number} 
    * @param var10 {Number} 
    * @param var11 {Number} 
    * @param var12 {Number} 
    * @param var13 {Number} 
    * @param var14 {Number} 
    * @param var15 {Number} 
    * @param var16 {Number} 
    */

    constructor(var1, var2, var3, var4, var5, var6, var8, var9, var10, var11, var12, var13, var14, var15, var16) {
        
        
        this['var1'] = var1;
        this['var2'] = var2;
        this['var3'] = var3;
        this['var4'] = var4;
        this['var5'] = var5;
        this['var6'] = var6;
        this['var8'] = var8;
        this['var9'] = var9;
        this['var10'] = var10;
        this['var11'] = var11;
        this['var12'] = var12;
        this['var13'] = var13;
        this['var14'] = var14;
        this['var15'] = var15;
        this['var16'] = var16;
        
    }

    /**
    * Constructs a <code>SurfaceValue</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SurfaceValue} obj Optional instance to populate.
    * @return {module:model/SurfaceValue} The populated <code>SurfaceValue</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SurfaceValue();
                        
            
            if (data.hasOwnProperty('var1')) {
                obj['var1'] = ApiClient.convertToType(data['var1'], 'Number');
            }
            if (data.hasOwnProperty('var2')) {
                obj['var2'] = ApiClient.convertToType(data['var2'], 'Number');
            }
            if (data.hasOwnProperty('var3')) {
                obj['var3'] = ApiClient.convertToType(data['var3'], 'Number');
            }
            if (data.hasOwnProperty('var4')) {
                obj['var4'] = ApiClient.convertToType(data['var4'], 'Number');
            }
            if (data.hasOwnProperty('var5')) {
                obj['var5'] = ApiClient.convertToType(data['var5'], 'Number');
            }
            if (data.hasOwnProperty('var6')) {
                obj['var6'] = ApiClient.convertToType(data['var6'], 'Number');
            }
            if (data.hasOwnProperty('var8')) {
                obj['var8'] = ApiClient.convertToType(data['var8'], 'Number');
            }
            if (data.hasOwnProperty('var9')) {
                obj['var9'] = ApiClient.convertToType(data['var9'], 'Number');
            }
            if (data.hasOwnProperty('var10')) {
                obj['var10'] = ApiClient.convertToType(data['var10'], 'Number');
            }
            if (data.hasOwnProperty('var11')) {
                obj['var11'] = ApiClient.convertToType(data['var11'], 'Number');
            }
            if (data.hasOwnProperty('var12')) {
                obj['var12'] = ApiClient.convertToType(data['var12'], 'Number');
            }
            if (data.hasOwnProperty('var13')) {
                obj['var13'] = ApiClient.convertToType(data['var13'], 'Number');
            }
            if (data.hasOwnProperty('var14')) {
                obj['var14'] = ApiClient.convertToType(data['var14'], 'Number');
            }
            if (data.hasOwnProperty('var15')) {
                obj['var15'] = ApiClient.convertToType(data['var15'], 'Number');
            }
            if (data.hasOwnProperty('var16')) {
                obj['var16'] = ApiClient.convertToType(data['var16'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} var1
    */
    'var1' = undefined;
    /**
    * @member {Number} var2
    */
    'var2' = undefined;
    /**
    * @member {Number} var3
    */
    'var3' = undefined;
    /**
    * @member {Number} var4
    */
    'var4' = undefined;
    /**
    * @member {Number} var5
    */
    'var5' = undefined;
    /**
    * @member {Number} var6
    */
    'var6' = undefined;
    /**
    * @member {Number} var8
    */
    'var8' = undefined;
    /**
    * @member {Number} var9
    */
    'var9' = undefined;
    /**
    * @member {Number} var10
    */
    'var10' = undefined;
    /**
    * @member {Number} var11
    */
    'var11' = undefined;
    /**
    * @member {Number} var12
    */
    'var12' = undefined;
    /**
    * @member {Number} var13
    */
    'var13' = undefined;
    /**
    * @member {Number} var14
    */
    'var14' = undefined;
    /**
    * @member {Number} var15
    */
    'var15' = undefined;
    /**
    * @member {Number} var16
    */
    'var16' = undefined;




}
