/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SurfaceValue from './SurfaceValue';

/**
* The SurfaceAggregate model module.
* @module model/SurfaceAggregate
* @version 3.0.3
*/
export default class SurfaceAggregate {
    /**
    * Constructs a new <code>SurfaceAggregate</code>.
    * @alias module:model/SurfaceAggregate
    * @class
    * @param dt {Date} 
    * @param delta {String} 
    * @param values {module:model/SurfaceValue} 
    */

    constructor(dt, delta, values) {
        
        
        this['dt'] = dt;
        this['delta'] = delta;
        this['values'] = values;
        
    }

    /**
    * Constructs a <code>SurfaceAggregate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SurfaceAggregate} obj Optional instance to populate.
    * @return {module:model/SurfaceAggregate} The populated <code>SurfaceAggregate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SurfaceAggregate();
                        
            
            if (data.hasOwnProperty('dt')) {
                obj['dt'] = ApiClient.convertToType(data['dt'], 'Date');
            }
            if (data.hasOwnProperty('delta')) {
                obj['delta'] = ApiClient.convertToType(data['delta'], 'String');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = SurfaceValue.constructFromObject(data['values']);
            }
        }
        return obj;
    }

    /**
    * @member {Date} dt
    */
    'dt' = undefined;
    /**
    * @member {String} delta
    */
    'delta' = undefined;
    /**
    * @member {module:model/SurfaceValue} values
    */
    'values' = undefined;




}
