/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Token model module.
* @module model/Token
* @version 3.0.3
*/
export default class Token {
    /**
    * Constructs a new <code>Token</code>.
    * @alias module:model/Token
    * @class
    * @param accessToken {String} 
    * @param tokenType {String} 
    */

    constructor(accessToken, tokenType) {
        
        
        this['access_token'] = accessToken;
        this['token_type'] = tokenType;
        
    }

    /**
    * Constructs a <code>Token</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Token} obj Optional instance to populate.
    * @return {module:model/Token} The populated <code>Token</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Token();
                        
            
            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
            if (data.hasOwnProperty('token_type')) {
                obj['token_type'] = ApiClient.convertToType(data['token_type'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} access_token
    */
    'access_token' = undefined;
    /**
    * @member {String} token_type
    */
    'token_type' = undefined;




}
