/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The UpdatePassword model module.
* @module model/UpdatePassword
* @version 3.0.3
*/
export default class UpdatePassword {
    /**
    * Constructs a new <code>UpdatePassword</code>.
    * @alias module:model/UpdatePassword
    * @class
    * @param password {String} 
    * @param newPassword {String} 
    */

    constructor(password, newPassword) {
        
        
        this['password'] = password;
        this['new_password'] = newPassword;
        
    }

    /**
    * Constructs a <code>UpdatePassword</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UpdatePassword} obj Optional instance to populate.
    * @return {module:model/UpdatePassword} The populated <code>UpdatePassword</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdatePassword();
                        
            
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('new_password')) {
                obj['new_password'] = ApiClient.convertToType(data['new_password'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} password
    */
    'password' = undefined;
    /**
    * @member {String} new_password
    */
    'new_password' = undefined;




}
