/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import HeartBeat from '../model/HeartBeat';

/**
* APIHealth service.
* @module api/APIHealthApi
* @version 3.0.3
*/
export default class APIHealthApi {

    /**
    * Constructs a new APIHealthApi. 
    * @alias module:api/APIHealthApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getHeartbeat operation.
     * @callback module:api/APIHealthApi~getHeartbeatCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HeartBeat} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Heartbeat
     * @param {module:api/APIHealthApi~getHeartbeatCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HeartBeat}
     */
    getHeartbeat(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = HeartBeat;

      return this.apiClient.callApi(
        '/heartbeat', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
