/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IVolApi);
  }
}(this, function(expect, IVolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IVolApi.RawOptionPy();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RawOptionPy', function() {
    it('should create an instance of RawOptionPy', function() {
      // uncomment below and update the code to test RawOptionPy
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be.a(IVolApi.RawOptionPy);
    });

    it('should have the property ust (base name: "ust")', function() {
      // uncomment below and update the code to test the property ust
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property exchange (base name: "exchange")', function() {
      // uncomment below and update the code to test the property exchange
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property symbol (base name: "symbol")', function() {
      // uncomment below and update the code to test the property symbol
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property ltd (base name: "ltd")', function() {
      // uncomment below and update the code to test the property ltd
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property putcall (base name: "putcall")', function() {
      // uncomment below and update the code to test the property putcall
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property strkpx (base name: "strkpx")', function() {
      // uncomment below and update the code to test the property strkpx
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property metric (base name: "metric")', function() {
      // uncomment below and update the code to test the property metric
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property startdate (base name: "startdate")', function() {
      // uncomment below and update the code to test the property startdate
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property enddate (base name: "enddate")', function() {
      // uncomment below and update the code to test the property enddate
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property optionMonth (base name: "option_month")', function() {
      // uncomment below and update the code to test the property optionMonth
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property underlyingMonth (base name: "underlying_month")', function() {
      // uncomment below and update the code to test the property underlyingMonth
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property dminus (base name: "dminus")', function() {
      // uncomment below and update the code to test the property dminus
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

    it('should have the property order (base name: "order")', function() {
      // uncomment below and update the code to test the property order
      //var instane = new IVolApi.RawOptionPy();
      //expect(instance).to.be();
    });

  });

}));
