/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IVolApi);
  }
}(this, function(expect, IVolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IVolApi.VolaSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VolaSummary', function() {
    it('should create an instance of VolaSummary', function() {
      // uncomment below and update the code to test VolaSummary
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be.a(IVolApi.VolaSummary);
    });

    it('should have the property symbol (base name: "symbol")', function() {
      // uncomment below and update the code to test the property symbol
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "start_date")', function() {
      // uncomment below and update the code to test the property startDate
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "end_date")', function() {
      // uncomment below and update the code to test the property endDate
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property delta (base name: "delta")', function() {
      // uncomment below and update the code to test the property delta
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property expiry (base name: "expiry")', function() {
      // uncomment below and update the code to test the property expiry
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property standardDev (base name: "standard_dev")', function() {
      // uncomment below and update the code to test the property standardDev
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property average (base name: "average")', function() {
      // uncomment below and update the code to test the property average
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property min (base name: "min")', function() {
      // uncomment below and update the code to test the property min
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property max (base name: "max")', function() {
      // uncomment below and update the code to test the property max
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property observations (base name: "observations")', function() {
      // uncomment below and update the code to test the property observations
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property last (base name: "last")', function() {
      // uncomment below and update the code to test the property last
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property weekAgoOne (base name: "week_ago_one")', function() {
      // uncomment below and update the code to test the property weekAgoOne
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property weekAgoTwo (base name: "week_ago_two")', function() {
      // uncomment below and update the code to test the property weekAgoTwo
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property weekAgoThree (base name: "week_ago_three")', function() {
      // uncomment below and update the code to test the property weekAgoThree
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property weekAgoFour (base name: "week_ago_four")', function() {
      // uncomment below and update the code to test the property weekAgoFour
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property weekAgoFive (base name: "week_ago_five")', function() {
      // uncomment below and update the code to test the property weekAgoFive
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

    it('should have the property weekAgoSix (base name: "week_ago_six")', function() {
      // uncomment below and update the code to test the property weekAgoSix
      //var instane = new IVolApi.VolaSummary();
      //expect(instance).to.be();
    });

  });

}));
