/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IVolApi);
  }
}(this, function(expect, IVolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IVolApi.ImpliedVolatilityApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ImpliedVolatilityApi', function() {
    describe('getAtmIvol', function() {
      it('should call getAtmIvol successfully', function(done) {
        //uncomment below and update the code to test getAtmIvol
        //instance.getAtmIvol(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getInterSpread', function() {
      it('should call getInterSpread successfully', function(done) {
        //uncomment below and update the code to test getInterSpread
        //instance.getInterSpread(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIvol', function() {
      it('should call getIvol successfully', function(done) {
        //uncomment below and update the code to test getIvol
        //instance.getIvol(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIvolCalendar', function() {
      it('should call getIvolCalendar successfully', function(done) {
        //uncomment below and update the code to test getIvolCalendar
        //instance.getIvolCalendar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIvolSmile', function() {
      it('should call getIvolSmile successfully', function(done) {
        //uncomment below and update the code to test getIvolSmile
        //instance.getIvolSmile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIvolSummaryCme', function() {
      it('should call getIvolSummaryCme successfully', function(done) {
        //uncomment below and update the code to test getIvolSummaryCme
        //instance.getIvolSummaryCme(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIvolSummaryEurex', function() {
      it('should call getIvolSummaryEurex successfully', function(done) {
        //uncomment below and update the code to test getIvolSummaryEurex
        //instance.getIvolSummaryEurex(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIvolSummaryIce', function() {
      it('should call getIvolSummaryIce successfully', function(done) {
        //uncomment below and update the code to test getIvolSummaryIce
        //instance.getIvolSummaryIce(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIvolSummarySingle', function() {
      it('should call getIvolSummarySingle successfully', function(done) {
        //uncomment below and update the code to test getIvolSummarySingle
        //instance.getIvolSummarySingle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIvolSummaryUsetf', function() {
      it('should call getIvolSummaryUsetf successfully', function(done) {
        //uncomment below and update the code to test getIvolSummaryUsetf
        //instance.getIvolSummaryUsetf(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRiskReversal', function() {
      it('should call getRiskReversal successfully', function(done) {
        //uncomment below and update the code to test getRiskReversal
        //instance.getRiskReversal(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSurfaceByDelta', function() {
      it('should call getSurfaceByDelta successfully', function(done) {
        //uncomment below and update the code to test getSurfaceByDelta
        //instance.getSurfaceByDelta(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
