/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IVolApi);
  }
}(this, function(expect, IVolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IVolApi.InfoApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InfoApi', function() {
    describe('getApiInfoExchanges', function() {
      it('should call getApiInfoExchanges successfully', function(done) {
        //uncomment below and update the code to test getApiInfoExchanges
        //instance.getApiInfoExchanges(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiInfoFirstAndLast', function() {
      it('should call getApiInfoFirstAndLast successfully', function(done) {
        //uncomment below and update the code to test getApiInfoFirstAndLast
        //instance.getApiInfoFirstAndLast(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiInfoLtd', function() {
      it('should call getApiInfoLtd successfully', function(done) {
        //uncomment below and update the code to test getApiInfoLtd
        //instance.getApiInfoLtd(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiInfoOptionMonthAndUnderlyingMonth', function() {
      it('should call getApiInfoOptionMonthAndUnderlyingMonth successfully', function(done) {
        //uncomment below and update the code to test getApiInfoOptionMonthAndUnderlyingMonth
        //instance.getApiInfoOptionMonthAndUnderlyingMonth(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiInfoSymbols', function() {
      it('should call getApiInfoSymbols successfully', function(done) {
        //uncomment below and update the code to test getApiInfoSymbols
        //instance.getApiInfoSymbols(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiInfoUsts', function() {
      it('should call getApiInfoUsts successfully', function(done) {
        //uncomment below and update the code to test getApiInfoUsts
        //instance.getApiInfoUsts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postApiInfoStrikes', function() {
      it('should call postApiInfoStrikes successfully', function(done) {
        //uncomment below and update the code to test postApiInfoStrikes
        //instance.postApiInfoStrikes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
