/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IVolApi);
  }
}(this, function(expect, IVolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IVolApi.PriceDataApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PriceDataApi', function() {
    describe('getContinuousEod', function() {
      it('should call getContinuousEod successfully', function(done) {
        //uncomment below and update the code to test getContinuousEod
        //instance.getContinuousEod(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContinuousEodAsArray', function() {
      it('should call getContinuousEodAsArray successfully', function(done) {
        //uncomment below and update the code to test getContinuousEodAsArray
        //instance.getContinuousEodAsArray(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContinuousEodSpread', function() {
      it('should call getContinuousEodSpread successfully', function(done) {
        //uncomment below and update the code to test getContinuousEodSpread
        //instance.getContinuousEodSpread(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getIntradayPrices', function() {
      it('should call getIntradayPrices successfully', function(done) {
        //uncomment below and update the code to test getIntradayPrices
        //instance.getIntradayPrices(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPvpIntraday', function() {
      it('should call getPvpIntraday successfully', function(done) {
        //uncomment below and update the code to test getPvpIntraday
        //instance.getPvpIntraday(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRegularFuturesEod', function() {
      it('should call getRegularFuturesEod successfully', function(done) {
        //uncomment below and update the code to test getRegularFuturesEod
        //instance.getRegularFuturesEod(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
