/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IVolApi);
  }
}(this, function(expect, IVolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IVolApi.RawDataApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RawDataApi', function() {
    describe('getAllOptionsSingleUnderlyingSingleDay', function() {
      it('should call getAllOptionsSingleUnderlyingSingleDay successfully', function(done) {
        //uncomment below and update the code to test getAllOptionsSingleUnderlyingSingleDay
        //instance.getAllOptionsSingleUnderlyingSingleDay(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postDeltaData', function() {
      it('should call postDeltaData successfully', function(done) {
        //uncomment below and update the code to test postDeltaData
        //instance.postDeltaData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postRawOptionData', function() {
      it('should call postRawOptionData successfully', function(done) {
        //uncomment below and update the code to test postRawOptionData
        //instance.postRawOptionData(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postTopOiAndVolume', function() {
      it('should call postTopOiAndVolume successfully', function(done) {
        //uncomment below and update the code to test postTopOiAndVolume
        //instance.postTopOiAndVolume(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
