/**
 * iVolAPI
 * implied volatility and price data for selected ETFs and futures. Contact: info at volsurf.com
 *
 * OpenAPI spec version: 3.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IVolApi);
  }
}(this, function(expect, IVolApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IVolApi.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('deleteApiUser', function() {
      it('should call deleteApiUser successfully', function(done) {
        //uncomment below and update the code to test deleteApiUser
        //instance.deleteApiUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserRole', function() {
      it('should call deleteUserRole successfully', function(done) {
        //uncomment below and update the code to test deleteUserRole
        //instance.deleteUserRole(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiUsers', function() {
      it('should call getApiUsers successfully', function(done) {
        //uncomment below and update the code to test getApiUsers
        //instance.getApiUsers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserRoles', function() {
      it('should call getUserRoles successfully', function(done) {
        //uncomment below and update the code to test getUserRoles
        //instance.getUserRoles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postAddNewApiUser', function() {
      it('should call postAddNewApiUser successfully', function(done) {
        //uncomment below and update the code to test postAddNewApiUser
        //instance.postAddNewApiUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putAddUserRole', function() {
      it('should call putAddUserRole successfully', function(done) {
        //uncomment below and update the code to test putAddUserRole
        //instance.putAddUserRole(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putChangeUserPw', function() {
      it('should call putChangeUserPw successfully', function(done) {
        //uncomment below and update the code to test putChangeUserPw
        //instance.putChangeUserPw(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
